name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Copy build to build branch
        run: |
          git checkout build
          rm -rf *
          cp -r build/. .
          git add .
          git commit -m "Update build"
          git push origin build
